version: '3' 
 volumes: 
    portainer_data: 
 services: 
    jupyter: 
       image: lewis9914/midterm_review 
       environment: 
          - JUPYTER_ENABLE_LAB=yes 
          - JUPYTER_TOKEN=bdp2_password 
          - CHOWN_HOME=yes 
          - CHOWN_HOME_OPTS=-R 
       networks: 
          - backend 
          - frontend 
       user: root 
       volumes: 
          - ~/review/work:/home/jovyan 
       ports: 
         - 80:8888 
    redis: 
       image: redis 
       command: redis-server 
       volumes: 
          - ~/review/work:/data 
       networks: 
          - backend 
    portainer: 
       image: portainer/portainer-ce 
       container_name: portainer 
       restart: always 
       volumes: 
          - /var/run/docker.sock:/var/run/docker.sock 
          - portainer_data:/data portainer/portainer-ce 
       networks: 
          - frontend 
       ports: 
          - 8000:8000 
          - 443:9443 
  
 networks: 
   backend: 
       driver: bridge 
   frontend: 
       driver: bridge
